name: Server CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  server-setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Set up Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: '20' 
          cache: 'npm' 

      - name: Install server dependencies
        run: npm ci
        working-directory: ./server

      - name: Start server
        run: npm start 
        working-directory: ./server
